import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar/page";
import Footer from "./components/Footer/page";
import { CartProvider } from "./context/page";



export const metadata: Metadata = {
  title: "Fashion",
  description: "Generated by Fiza Sohail",
};

export default function RootLayout({
children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       <CartProvider>
       <Navbar />
        {children}
        <Footer />
       </CartProvider>
      </body>
    </html>
  );
}
